baseURL = "http://ngodingkuy.me/"
languageCode = "en-us"
title = "Ngoding Kuy!"

description = "Jalan Termudah untuk Memecahkan Masalah"

theme = "ngodingkuy"
relativeURLs = true
summaryLength = 5
tag = "tags"
category = "categories"

disqusShortname = "ngodingkuy"

[author]
    name = "Dhymas Julyan Riyanto"
    homepage = "https://github.com/dhymasriyanto"
    bio = "My Mother always tells me to smile and put on happy face"
    image = "https://avatars0.githubusercontent.com/u/32106219?s=460&v=4"


[menu]
    [[menu.main]]
    identifier = "beranda"
    name = "Beranda"
    url = "/"
    weight = 100

    [[menu.main]]
    identifier = "posts"
    name = "Postingan"
    url = "/posts/"
    weight = 110

    [[menu.main]]
    identifier = "tentang"
    name = "Tentang"
    url = "/tentang/"
    weight = 130

    [[menu.main]]
    identifier = "categories"
    name = "Kategori"
    url = "/categories/"
    weight = 120

    
