baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ngoding Kuy!"
theme = "ngodingkuy"
relativeURLs = true
summaryLength = 10
tag = "tags"
category = "categories"

[menu]
    [[menu.main]]
    identifier = "beranda"
    name = "Beranda"
    url = "/"
    weight = 100

    [[menu.main]]
    identifier = "posts"
    name = "Postingan"
    url = "/posts/"
    weight = 110

    [[menu.main]]
    identifier = "tentang"
    name = "Tentang"
    url = "/tentang/"
    weight = 130

    [[menu.main]]
    identifier = "categories"
    name = "Kategori"
    url = "/categories/"
    weight = 120

    
