baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ngoding Kuy!"
theme = "ngodingkuy"
relativeURLs = true
summaryLength = 10

[menu]
    [[menu.main]]
    identifier = "beranda"
    name = "Beranda"
    url = "/"

    [[menu.main]]
    identifier = "terbaru"
    name = "Postingan"
    url = "/terbaru/"

    [[menu.main]]
    identifier = "tentang"
    name = "Tentang"
    url = "/tentang"

