backend:
  name: git-gateway
  repo: dhymasriyanto/dhymasriyanto.github.io
  branch: master # Branch to update (optional; defaults to master)

site_url: "https://www.ngodingkuy.me"

# publish_mode: editorial_workflow

media_folder: "content/posts/" # Folder where user uploaded files should go
# public_folder: "img/"

collections:
  - name: "posts"
    label: "Post"
    folder: "content/posts"
    slug: "{[slug}}"
    create: true
    fields: # The fields for each document, usually in front matter
      - { name: category, label: category, widget: "select", options: ["Test", "JavaScript", "Devops", "Company"] }
      - { name: date, label: Date, widget: date }
      - { name: title, label: title }
      - { name: "body", label: "Blog post content", widget: "markdown"}