backend:
  name: git-gateway
  repo: dhymasriyanto/dhymasriyanto.github.io
  branch: master # Branch to update (optional; defaults to master)

site_url: "https://www.ngodingkuy.me"

# publish_mode: editorial_workflow

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: /img

collections:
  - name: "posts"
    label: "Post"
    folder: "content/posts/"
    path: '{{slug}}/index'
    create: true
    extension: md
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { name: author, label: author }
      - { name: category, label: category, widget: "select", options: ["Test", "JavaScript", "Devops", "Company"] }
      - { name: date, label: Date, widget: date }
      - { name: title, label: title }
      - { name: "image", label: "Cover image", widget: "image"}
      - { name: "body", label: "Blog post content", widget: "markdown"}
