backend:
  name: git-gateway
  repo: dhymasriyanto/dhymasriyanto.github.io
  branch: master # Branch to update (optional; defaults to master)

site_url: "https://www.ngodingkuy.me"

# publish_mode: editorial_workflow

media_folder: "/content/posts/{{slug}}" # Folder where user uploaded files should go
# public_folder: "img/"

collections:
  - name: "posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    folder: "/content/posts/{{slug}}"
    media_folder: "/content/posts/{{slug}}"
    # media_folder: "/content/posts"
    fields: # The fields for each document, usually in front matter
      - { name: category, label: category, widget: "select", options: ["JVM", "JavaScript", "Devops", "Company"] }
      - { name: date, label: Date, widget: date }
      - { name: title, label: title }
      - { name: "body", label: "Blog post content", widget: "markdown"}