backend:
  name: git-gateway
  repo: dhymasriyanto/dhymasriyanto.github.io
  branch: master # Branch to update (optional; defaults to master)

site_url: "https://www.ngodingkuy.me"

# publish_mode: editorial_workflow

media_folder: "static/img/" # Folder where user uploaded files should go
public_folder: "img/"

collections:
  - name: posts # Used in routes, e.g., /admin/collections/blog
    label: Post # Used in the UI
    folder: "content/posts/{{slug}}"
    create: true # Allow users to create new documents in this collection
    extension: md
    format: frontmatter
    # preview_path: "docs/{{title}}"
    # slug: index # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { name: author, label: author }
      - { name: category, label: category, widget: "select", options: ["JVM", "JavaScript", "Devops", "Company"] }
      - { name: date, label: Date, widget: date }
      - { name: title, label: title }
      - { name: "body", label: "Blog post content", widget: "markdown"}